services:
  account-service:
    build: .
    container_name: account-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${SECRET_KEY}
    ports:
      - "8081:8080"
    networks:
      - microservices-net
networks:
  microservices-net:
    external: true