spring:
  application:
    name: accountService
  # Configuración de la base de datos MySQL para AccountService
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_db?useSSL=false&allowPublicKeyRetrieval=true
    username: mysqladminuser
    password: mysqladminpass

  # Configuración JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  kafka:
    #    bootstrap-servers: localhost:9092  #para local
    bootstrap-servers: kafka:29092
    consumer:
      group-id: accountGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
            user-created-event:com.microservice.accountService.kafka.event.UserCreatedEvent,
            transfer-requested-event:com.microservice.accountService.kafka.event.TransferRequestedEvent,
            transfer-debit-requested-event:com.microservice.accountService.kafka.event.TransferDebitRequestedEvent,
            transfer-credit-requested-event:com.microservice.accountService.kafka.event.TransferCreditRequestedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          funds-reserved-event:com.microservice.accountService.kafka.event.FundsReservedEvent,
          funds-reservation-failed-event:com.microservice.accountService.kafka.event.FundsReservationFailedEvent,
          funds-debited-event:com.microservice.accountService.kafka.event.FundsDebitedEvent,
          funds-debit-failed-event:com.microservice.accountService.kafka.event.FundsDebitFailedEvent,
          funds-credited-event:com.microservice.accountService.kafka.event.FundsCreditedEvent,
          funds-credit-failed-event:com.microservice.accountService.kafka.event.FundsCreditFailedEvent

server:
  port: 8080

jwt:
  secret: ${SECRET_KEY}

logging:
  pattern: # PARA EL CORRELATIONAL ID - LO MOSTRAMOS EN LOG PARA UN SEGUIMIENTO MÁS EFICIENTE Y POSIBLE DEBUG, ETC ETC
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [CID:%X{correlationId}] %-5level %logger - %msg%n"